#!/usr/bin/env bash
# -*- coding: utf-8 -*-
{ set +x; } 2>/dev/null

usage() {
    echo "usage: $(basename $0) path [comment]" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

[[ $# == 0 ]] && usage

( set -x; osascript "${BASH_SOURCE[0]%/*}"/.finder-comment.applescript "$@" )
