#!/usr/bin/env bash
#
# read/write Finder comment

usage() {
    echo "usage: $(basename $0) path [comment]" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

[[ $# == 0 ]] && usage

( set -x; osascript "${BASH_SOURCE[0]%/*}"/.finder-comment.applescript "$@" )
