#!/usr/bin/env bash
# -*- coding: utf-8 -*-
{ set +x; } 2>/dev/null

usage() {
    echo "usage: $(basename $0) path image" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

[[ $# != 2 ]] && usage

! [ -e "$1" ] && echo "ERROR: $1 NOT EXISTS" 1>&2 && exit 1
[[ -z "$2" ]] && echo "ERROR: image unknown" 1>&2 && exit 1
! [ -e "$2" ] && echo "ERROR: $2 NOT EXISTS" 1>&2 && exit 1

osascript "${BASH_SOURCE[0]%/*}"/.finder-icon.applescript "$@" || exit
[ -e "$1"/$'Icon\r' ] && { chflags hidden "$1"/$'Icon\r'; exit; };:
